name: Build and Deploy EC2

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine
    steps:
      - name: Install git
        run: apk --update add git tar
      - uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: npm-${{ hashFiles('package-lock.json') }}-v4
      - name: Install dependencies
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
      - name: Build
        run: npm run build
  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: build
      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo $SSH_PRIVATE_KEY | base64 -d > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Adding Known Hosts
        run: ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
      - name: Copy files to the server
        run: |
          rsync -a -r --progress --human-readable --delete
          build/* $SSH_USER@$SSH_HOST:~/realworld/public/
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
