name: Build and Deploy

on:
  push:
    branches: [master]

  # специальное событие, которое происходит при ручном вызове workflow
  workflow_dispatch:

jobs:
  # помним, что прежде всего, надо собрать фронтенд при помощи webpack
  build:
    runs-on: ubuntu-latest
    # укажем, что для этой job нам нужен специальный контейнет
    container:
      # возьмем Docker образ Node.js из публичного реестра
      image: node:16.15.0-alpine
    # последовательные задачи (шаги), важно помнить, что переменные окружения не сохраняются
    # между шагами и их нужно пробрасывать, если требуется.
    steps:
      # указываем action, который будет запущен как часть job
      # В текущем случае это клонирование репозитория
      - uses: actions/checkout@v3
      # Кеширование npm
      - name: Cache dependencies
        # включаем специальный action
        uses: actions/cache@v3
        # передаем параметры
        with:
          # что кешировать (путь)
          path: ~/.npm
          # ключ кеширования (хеш)
          key: npm-${{ hashFiles('package-lock.json') }}
          # ключ для восстановления кеша
          restore-keys: npm-
      - name: Install dependencies
        run: npm ci --ignore-scripts
      # Запуск сборки
      - name: Build
        run: npm run build
        env:
          REACT_APP_BACKEND_URL: ${{ secrets.API_URL }}
      # Теперь загружаем артефакты
      - name: Archive build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
  deploy:
    # укажем, что для деплоя нам нужно сначала собрать приложение
    needs: build
    runs-on: ubuntu-latest
    steps:
      # загружаем ранее сохраненные артефакты
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: build
      # Дальше по аналогии с backend, просто загружаем на сервер
      - name: Setup SSH
        run: |
          # создаем директорию для ключа
          mkdir -p ~/.ssh
          # выводим содержимое нашей переменной окружения в файл
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/free-aws-sshkey.pem
          # ставим нужные безопасные права
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/free-aws-sshkey.pem
          # Добавляем отпечаток сервера
          echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Copy files to the server
        run: |
          # воспользуемся SCP здесь, т.к. нам просто нужно загрузить из
          # одной директории
          scp -r build/* $SSH_USER@$SSH_HOST:~/realworld/public
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}